#!/bin/bash

cd ~
DIRECTORY="iti0201"

if [ "$#" != 3 ]; then
    echo "USAGE: robot_test [uni-id] [exercise_number] [map_number]"
    exit 0
fi

git_user_name=$1
exercise_number=$2
map_number=$3

git_address="https://gitlab.cs.ttu.ee/$git_user_name/$DIRECTORY.git"

echo $git_address

if [ -d "$DIRECTORY" ]; then
    echo "Repository already exists. Updating.."
    cd $DIRECTORY
    git pull
else
    echo "Repository doesn't exist yet. Creating one now..."
    git clone $git_address
    cd $DIRECTORY
fi

exercise_name=""
directory_name=""

if [ -d "$exercise_number" ]; then
    cd $exercise_number
else
    echo "Your files do not contain the $exercise_number folder."
    exit 1
fi

if ! [ -f "robot.py" ]; then
    echo "Your directory $exercise_number folder does not contain the necessary robot.py file."
    exit 1
fi

x-terminal-emulator -e roslaunch lego_gazebo lego.launch dir:=$exercise_number map:=$map_number

x-terminal-emulator -e script_launch $directory_name

#roslaunch lego_gazebo lego_$exercise_name.launch
