#!/bin/bash

cd ~
DIRECTORY="iti0201"

if [ "$#" -lt 3 ]; then
    echo "USAGE: robot_test [uni-id] [exercise_number] [map_number]"
    echo "You can also add optional arguments of [sonar_noise] and [gyro_noise]"
    exit 0
fi

git_user_name=$1
exercise_number=$2
map_number=$3

if [ -z "$4" ]; then
    sonar_noise=0
else
    sonar_noise=$4
fi

if [ -z "$5" ]; then
    gyro_noise=0
else
    gyro_noise=$5
fi

git_address="https://$git_user_name@gitlab.cs.ttu.ee/$git_user_name/$DIRECTORY.git"

echo $git_address

if [ -d "$DIRECTORY" ]; then
    echo "Repository already exists. Updating.."
    cd $DIRECTORY
    git pull
else
    echo "Repository doesn't exist yet. Creating one now..."
    git clone $git_address
    cd $DIRECTORY
fi

exercise_name=""
directory_name=""

if [ -d "$exercise_number" ]; then
    cd $exercise_number
else
    echo "Your files do not contain the $exercise_number folder."
    exit 1
fi

if ! [ -f "robot.py" ]; then
    echo "Your directory $exercise_number folder does not contain the necessary robot.py file."
    exit 1
fi

x-terminal-emulator -e roslaunch lego_gazebo lego.launch dir:=$exercise_number map:=$map_number sonar_noise:=$sonar_noise gyro_noise:=$gyro_noise

x-terminal-emulator -e script_launch $DIRECTORY/$exercise_number

#roslaunch lego_gazebo lego_$exercise_name.launch
